# Generated by Django 5.2.7 on 2025-10-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], help_text='Select whether the patient is an inpatient or outpatient.', max_length=20, null=True),
        ),
    ]
