# Generated by Django 5.0.6 on 2025-10-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='category',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('pharmacy', 'Pharmacy & Medicine'), ('lab', 'Laboratory'), ('other', 'Other')], default='consultation', max_length=50),
        ),
    ]
