# Generated by Django 5.0.6 on 2025-10-19 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_medicine_options_medicine_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.AddField(
            model_name='medicine',
            name='form',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('Powder', 'Powder'), ('Other', 'Other')], default='Other', help_text='Physical form of the medicine (Tablet, Capsule, Syrup, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(choices=[('Antibiotic', 'Antibiotic'), ('Analgesic', 'Analgesic'), ('Antipyretic', 'Antipyretic'), ('Antimalarial', 'Antimalarial'), ('Antifungal', 'Antifungal'), ('Antiviral', 'Antiviral'), ('Antacid', 'Antacid'), ('Antidiabetic', 'Antidiabetic'), ('Antihypertensive', 'Antihypertensive'), ('Vaccine', 'Vaccine'), ('Supplement', 'Supplement'), ('Cough Syrup', 'Cough Syrup'), ('Other', 'Other')], default='Other', help_text='Therapeutic category (Antibiotic, Painkiller, etc.)', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='pharmacy.supplier'),
        ),
    ]
