# Generated by Django 5.2.7 on 2025-10-16 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaff',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'lab_tech', 'imaging_tech', 'pharmacist', 'nurse']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
