# Generated by Django 5.0.6 on 2025-10-18 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaff',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'lab_tech', 'imaging_tech', 'pharmacist', 'nurse', 'hospital_admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='departmentstaff',
            index=models.Index(fields=['department'], name='departments_departm_1d8de4_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentstaff',
            index=models.Index(fields=['staff'], name='departments_staff_i_eafe26_idx'),
        ),
    ]
