# Generated by Django 5.2.7 on 2025-10-16 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='departmentstaff',
            index=models.Index(fields=['department'], name='departments_departm_1d8de4_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentstaff',
            index=models.Index(fields=['staff'], name='departments_staff_i_eafe26_idx'),
        ),
    ]
