# Generated by Django 5.2.7 on 2025-10-16 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_departmentstaff_departments_departm_1d8de4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentstaff',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'lab_tech', 'imaging_tech', 'pharmacist', 'nurse', 'hospital_admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
