# Generated by Django 5.0.6 on 2025-10-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_prescription_doctor_queue_alter_prescription_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='doctor_queue',
            new_name='queue_item',
        ),
    ]
