# Generated by Django 5.2.7 on 2025-10-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='department',
        ),
    ]
